spring.application.name=pr-reviewer

server.port=8081

# GitHub App config
github.app.id=${GITHUB_APP_ID}
github.app.private-key-path=${GITHUB_APP_PRIVATE_KEY_PATH}
github.webhook.secret=${GITHUB_WEBHOOK_SECRET}
github.api.base-url=https://api.github.com

# Groq LLM config
groq.api.key=${GROQ_API_KEY}
groq.api.base-url=https://api.groq.com/openai/v1
groq.model=llama-3.3-70b-versatile

# Redis Cloud
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.timeout=5000
spring.data.redis.ssl.enabled=true

logging.level.com.pr_reviewer.prreviewer = DEBUG
logging.level.org.springframework.web.reactive.function.client=DEBUG
