spring.application.name=pr-reviewer

server.port=8081

# GitHub App config
github.app.id=${GITHUB_APP_ID}
github.app.private-key-path=${GITHUB_APP_PRIVATE_KEY_PATH}
github.webhook.secret=${GITHUB_WEBHOOK_SECRET}
github.api.base-url=https://api.github.com

# Groq LLM config
groq.api.key=${GROQ_API_KEY}
groq.api.base-url=https://api.groq.com/openai/v1
groq.model=llama-3.3-70b-versatile

# Redis Cloud
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.timeout=5000

logging.level.com.pr_reviewer.prreviewer = DEBUG
logging.level.org.springframework.web.reactive.function.client=DEBUG

# Postgres + pgvector
spring.datasource.url=jdbc:postgresql://localhost:5433/prreviewer
spring.datasource.username=postgres
spring.datasource.password=postgres

# Spring AI - Google GenAI embeddings
spring.ai.google.genai.embedding.api-key=${GOOGLE_API_KEY}
spring.ai.google.genai.embedding.text.options.model=gemini-embedding-001
spring.ai.google.genai.embedding.text.options.dimensions=768

# Spring AI - pgvector store
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=768